# Generated by Django 2.2.27 on 2022-03-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220310_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=256, null=True),
        ),
    ]
