# Generated by Django 2.2.27 on 2022-03-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'student'), (2, 'admin'), (3, 'superadmin')], default=1),
        ),
    ]
