# Generated by Django 2.2.27 on 2022-04-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
