# Generated by Django 2.2.27 on 2022-03-10 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HighSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Recapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recapp', models.FileField(blank=True, default='', upload_to='')),
                ('recapp_cover', models.ImageField(blank=True, default='', upload_to='')),
                ('recapp_year', models.CharField(max_length=10)),
                ('is_approved', models.BooleanField(default=False)),
                ('zip_code', models.IntegerField(blank=True)),
                ('high_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yearbook.HighSchool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecappVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos', models.FileField(upload_to='')),
                ('recapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yearbook.Recapp')),
            ],
        ),
        migrations.CreateModel(
            name='RecappQuotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotes', models.FileField(upload_to='')),
                ('recapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yearbook.Recapp')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRecapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('cardholder_name', models.CharField(max_length=50)),
                ('expiry', models.DateField()),
                ('cvc', models.CharField(max_length=4)),
                ('status', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HighSchoolID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default='', upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
