# Generated by Django 2.2.27 on 2022-03-10 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0002_purchaserecapp_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserecapp',
            name='recapp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yearbook.Recapp'),
            preserve_default=False,
        ),
    ]
