# Generated by Django 2.2.27 on 2022-03-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0003_purchaserecapp_recapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('cardholder_name', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=16)),
                ('expiry', models.DateField()),
                ('cvc', models.CharField(max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchaserecapp',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='purchaserecapp',
            name='cardholder_name',
        ),
        migrations.RemoveField(
            model_name='purchaserecapp',
            name='cvc',
        ),
        migrations.RemoveField(
            model_name='purchaserecapp',
            name='expiry',
        ),
        migrations.RemoveField(
            model_name='purchaserecapp',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='purchaserecapp',
            name='last_name',
        ),
        migrations.AddField(
            model_name='purchaserecapp',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
