# Generated by Django 2.2.27 on 2022-03-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0004_auto_20220310_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserecapp',
            name='price',
        ),
        migrations.AddField(
            model_name='recapp',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
