# Generated by Django 2.2.27 on 2022-03-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0006_creditcards_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recapp',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='highschoolid',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='recapp',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
