# Generated by Django 2.2.27 on 2022-03-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0008_auto_20220318_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcards',
            name='expiry',
            field=models.DateField(),
        ),
    ]
