# Generated by Django 2.2.27 on 2022-04-01 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yearbook', '0012_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearbookCommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yearbook.HighSchool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
