# Generated by Django 2.2.27 on 2022-05-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0017_auto_20220406_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearbookcommittee',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
