# Generated by Django 2.2.27 on 2022-05-06 17:22

from django.db import migrations, models
import yearbook.models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0018_yearbookcommittee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='highschool',
            name='code',
            field=models.CharField(default=yearbook.models.code_generator, max_length=16),
        ),
        migrations.AlterField(
            model_name='highschoolid',
            name='code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
